### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Jeru2023** [ssbuild/chatglm3_finetuning#13]
I'm using a single RTX 4090, is it sufficient for the finetuning? if yes how to optimize the settings to avoid OOM?

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1016.00 MiB (GPU 0; 23.99 GiB total capacity; 22.27 GiB already allocated; 0 bytes free; 22.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by ssbuild** [comment]
lower length  or qlora

**Comment by Jeru2023** [comment]
> lower length or qlora

Where is the config? I don't find it in either train_lora.sh or train_xx.yaml yet.

**Comment by ssbuild** [comment]
modify train_lora.sh export load_in_bit=0

if in windows , try wsl2 + nvidia-docker

**Comment by Jeru2023** [comment]
already set load_init_bit=4, still got same error, the key is I only have 24G GPU memory, however 22.28G already reserved by Pytorch, this is too much. No matter how to optimize the param, i only have less than 2G memory remained, that's not sufficient for sure, so the question is why Pytorch reserve this much memory and How can i change this behavior?

**Comment by ssbuild** [comment]
dup #31
