### ISSUE TITLE
cannot import name 'TrainingArgumentsHF' from 'deep_training.data_helper'

### ISSUE THREAD

**Issue by Happzy-WHU** [ssbuild/chatglm3_finetuning#23]
![image](https://github.com/ssbuild/chatglm3_finetuning/assets/43106499/c41434ed-1c5c-4ed2-a3c9-b1163898495e)

**Comment by ssbuild** [comment]
pip list ｜grep ing

**Comment by Happzy-WHU** [comment]
> pip list ｜grep ing

(glm) zhongyuan_peng@A40-36-111-142-184:~$ pip list |grep ing
deep-training            0.1.13
huggingface-hub          0.17.3
lightning                2.0.2
lightning-cloud          0.5.34
lightning-utilities      0.8.0
packaging                23.1
pyparsing                3.0.9
pytorch-lightning        2.0.1.post0
typing_extensions        4.5.0
typing-inspect           0.9.0

**Comment by ssbuild** [comment]
pip install -U aigc-zoo

**Comment by Happzy-WHU** [comment]
> pip install -U aigc-zoo
👍
