### ISSUE TITLE
推理错误

### ISSUE THREAD

**Issue by Happzy-WHU** [ssbuild/chatglm3_finetuning#28]
![image](https://github.com/ssbuild/chatglm3_finetuning/assets/43106499/14befd74-af43-4b9d-be56-4cdc7e8cc514)

在lora训练后进行推理时，总是会出先[gMASK]x、[gMASK]V、[gMASK]O、[gMASK]sop[gMASK]\u0018。可以知道是为什么吗？

**Comment by Happzy-WHU** [comment]
一部分尝试5次推理还是会失败，对应上图中的空串。

**Comment by Happzy-WHU** [comment]
![image](https://github.com/ssbuild/chatglm3_finetuning/assets/43106499/4d4f65b7-30ef-4caa-ae7a-0017347cd59a)
这个是推理的参数。

**Comment by ssbuild** [comment]
你的代码是否更新到新代码了，我记得至少是有这个问题。

**Comment by Happzy-WHU** [comment]
> 你的代码是否更新到新代码了，我记得之前是有这个问题。

更新代码后解决了👍
